### PR TITLE
#162162998 Create descriptive validation error messages on user registration

### PR DESCRIPTION
**Pull request by billkabanga**
**What does this PR do?**
- Write tests for error messages.
- Modify error message for invalid email using extra_kwargs dictionary.
- Change the password field from Charfield to Regexfield.
- Override default password error messages with descriptive messages.
- Refactor tests.

**Description of the task to be completed?**

- Override default validation error messages to create more descriptive messages on user registration when invalid user parameters are provided.

**How should this be manually tested?**
- Pull the branch to your remote workspace.
- Run the server using `python manage.py runserver`
- Open POSTMAN.
- Add ```api/users/``` to the server URL.
- Add a JSON object with invalid parameters in the raw section of the body and POST
```
Please use the format below.
{
  "user": {
        "email": "tada@tada.tada",
        "username": "tada",
        "password": "password123",
  }
}

```
Use invalid parameters like: 
- Password less than 8 characters
- Non-alphanumeric password(eg helo#$#$%)
- Invalid email (eg tada.tada)
- On successful registration, try registering again.

**Relevant pivotal tracker stories?**
#13

### CODE REVIEW

**Comment by aayebare** [comment]
great descriptive messages ...and  thanks for the changes

**Review by Luleherll — COMMENTED** [review]
Good work @billkabanga

**Review by arthurarty — APPROVED** [review]
These changes have brought back our maintainability from D back to A. Good work guys.

**Comment by okellogabrielinnocent** [comment]
Nice work. Yesterday I was getting worried when it was taking long to complete checks

**Review by aayebare — APPROVED** [review]

**Review by okellogabrielinnocent — APPROVED** [review]

**Pull request merged**
