### PR TITLE
#162163015 Implement social share of article

### PR DESCRIPTION
**Pull request by okellogabrielinnocent**
### What does this PR do?
- Implement facebook, twitter and email share of an Author's heaven article
### Description of Task to be completed?
- Build facebook share endpoint
- Build twitter share endpoint
- Build an email share endpoint
- Write tests for this feature's functionality
### How should this be manually tested?
- On your local machine, checkout the develop branch using
```git checkout develop```
command , then pull the changes using
```git pull```
command
- Checkout this feature's branch using
```git checkout ft-share-articles-162163015```
- Open your editor and locate the project workspace.
- Activate a virtual environment and install the dependencies using `pip install -r requirements.txt` command
- Create a Postgres database called ahdb and make migrations by running:
       -
```python manage.py makemigrations```
and then
       -
```python manage.py migrate```
- Run the server using `python manage.py runserver`
##### Email
-  With a valid user account, create an article using swagger docs at `http://127.0.0.1:8000/docs/`
- Try this POST endpoint `/api/{slug}/email`
-   On postman with `http://localhost:8000/api/{slug}/email` route.
-   On swagger doc pass in the slug of article in the slug field and execute

*Sample data returned*
````
{
  "message": "Article successfully shared. Please check your email to view the article"
}
````
- Check your email to view the article's link
##### Facebook
-  Use the POST `/api/{slug}/facebook` endpoint

*Sample data returned*
````
{
  "message": "Article successfully shared on facebook",
  "link": "https://www.facebook.com/sharer/sharer.php?u=http://127.0.0.1:8000/api/articles/coding"
}
````

### What are the relevant pivotal tracker stories?
#162163015
##### Pair programmed by Gabriel and Mark

### CODE REVIEW

**Review by kizzanaome — APPROVED** [review]
LGTM

**Review by katunold — APPROVED** [review]
Well done guys

**Comment by Luleherll** [comment]
Nice work @okellogabrielinnocent @m-asiimwe

**Review by arthurarty — APPROVED** [review]
Great stuff getting this done.

**Pull request merged**
