### PR TITLE
#162162994  Setup and deploy base application to Heroku

### PR DESCRIPTION
**Pull request by billkabanga**
#### What does this PR do?
Setup and deploy base application to Heroku
#### Description of Task to be completed?
- Create Procfile
- Modify database settings with Django-Heroku and environment variables.
- Create a pipeline for staging and production environments.
- Deploy staging app on develop branch and production app on the master branch.
#### How should this be manually tested?
URL for staging app: [https://ah-backend-poseidon-staging.herokuapp.com/](url)
URL for production app: [https://ah-backend-poseidon.herokuapp.com/](url)
eg. When using the URLs add `admin/` or `/api/user`
#### What are the relevant pivotal tracker stories?
#162162994

### CODE REVIEW

**Comment by Luleherll** [comment]
The links to Heroku in the PR are broken.
 ## I have tried to copy and paste and it works. Seems the problem is with Github.

**Comment by aayebare** [comment]
URL links return 404, Not found. Is this supposed to happen?

**Comment by billkabanga** [comment]
@m-asiimwe @Luleherll When you follow the manual test guide the links should work.
Try something like this and see [https://ah-backend-poseidon-staging.herokuapp.com/admin/](url)
Let me know if it works.

**Comment by aayebare** [comment]
Much appreciated. working fine.

**Comment by okellogabrielinnocent** [comment]
This is good work @billkabanga

**Pull request merged**
